<a href="https://colab.research.google.com/github/K-Viera/Phyton/blob/main/FirstSteps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# First Steps


In [ ]:
print("hello world")

hello world


In [ ]:
x=5
y="kevin"
print(type(x))
print(type(y))
print(x,y) #have a space by default
# print(x + y) not possible because have diferent data types
print(str(x)+" "+y)


<class 'int'>
<class 'str'>
5 kevin
5 kevin


### Randoms

In [ ]:
#to use random we need to import a built-in module
import random
print(random.randrange(1,10))
print(random.randrange(1,10))
print(random.randrange(1,10))
print(random.randrange(1,10))
print(random.randrange(1,10))

9
4
6
1
3


## Functions


In [ ]:
def my_function(name="default name"):
  if name!="default name":
    print("hello {}".format(name))
  return name

my_function("kevin")
my_function("viera")
print(my_function())

hello kevin
hello viera
default name


In [ ]:
def arbitrary_fuction(*names):
  print(type(names))
  print(names);
  # print(names[2]) Error because the first function call only set 1 argument

arbitrary_fuction("kevin");
arbitrary_fuction("Kevin","viera")
arbitrary_fuction("kevin","Viera",3)

<class 'tuple'>
('kevin',)
<class 'tuple'>
('Kevin', 'viera')
<class 'tuple'>
('kevin', 'Viera', 3)


### Lambda functions
Is a small anonymous fuction

In [ ]:
x = lambda a : a + 10
print(x(5))
x = lambda a, b : a * b
print(x(5, 6))

15
30


## Class and objects






In [ ]:
class Student:
  #class attribute, donot change in instanctiation 
  classMessage="Hello World" 

  def __init__(self, name, major, gpa, is_on_probation):
    self.name = name
    self.major = major
    self.__gpa=gpa
    self.is_on_probation=is_on_probation

  def changeGPA(self,gpa):
    #Phyton allow create global variable inside functions
    global lastGPA
    lastGPA=self.__gpa
    self.__gpa=gpa
  #we need to put this attribute above the method to make a class method
  @classmethod
  def helloWorld(cls):
    print(cls.classMessage)
  
  #Static method (same as C#) we put this attribute above
  @staticmethod
  def yourMessage(message):
    print(message)

  #Getters and setters in phyton
  #we use the attribute @property
  @property
  def gpa(self):
    return self.__gpa
  
  @gpa.setter
  def gpa(self,gpa):
    if gpa > 0:
      self.__gpa=gpa
    else:
      print("invalid gpa")

In [ ]:
student1=Student("jim","business",3,False)
print(student1.gpa)
student1.changeGPA(-3)
print(student1.gpa)
print(lastGPA)
student2=Student("Kevin","Engineering",1.5,True)
student2.changeGPA(2)
print(lastGPA)
student2.helloWorld()
student2.yourMessage("Hola")
#setter
student2.gpa=-2


3
-3
3
1.5
Hello World
Hola
invalid gpa


### Inheritance


In [ ]:
class Person:
  def __init__(self,fname,lname):
    self.firstname=fname
    self.lastname=lname
  def printName(self):
    print(self.firstname, self.lastname)
x=Person("kevin","viera")
x.printName()

kevin viera


In [ ]:
class Student(Person):
  def __init__(self,fname,lname,graduation):
    super().__init__(fname,lname)
    self.graduation=graduation
  
  def getGraduation(self):
    return self.graduation

y=Student("kevin2","viera2",2023)
y.printName()
print(y.getGraduation())

kevin2 viera2
2023


#Data Structures

## Tree


In [1]:
# Get from https://www.codecademy.com/learn/nonlinear-data-structures-python/modules/trees-python/cheatsheet

class TreeNode:
  def __init__(self,state):
    self.state=state
    self.children=[]
  
  def add_child(self,child_node):
    self.children.append(child_node)
  
  def remove_child(self,child_node):
    self.children=[child for child in self.children if child is not child_node ]

  def traverse(self):
    nodes_to_visit=[self]
    while len(nodes_to_visit) > 0:
      current_node=nodes_to_visit.pop()
      #function
      print(current_node.state)
      nodes_to_visit+=current_node.children

In [4]:
node1=TreeNode(1)
node2=TreeNode(2)
node3=TreeNode(3)
node1.add_child(node2)
node1.add_child(node3)
node1.traverse()

1
3
2


# External Modules


##NumPy


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
#np receive any array-like object
arr= np.array((1,2,3,4,5,6,7))
print(arr)
print(type(arr))
print(arr[:-2])
print(arr[2:])
print(arr[2:4])
print(arr[::2])
print(arr[1::2])
print(arr[::-2])

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
[1 2 3 4 5]
[3 4 5 6 7]
[3 4]
[1 3 5 7]
[2 4 6]
[7 5 3 1]


In [ ]:
##Multiple dimensions
a=np.array(1)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
